### ISSUE TITLE
handlebars problem

### ISSUE THREAD

**Issue by joraku** [oneteam-dev/react-oneteam#26]
https://github.com/oneteam-dev/react-oneteam/network/alert/yarn.lock/handlebars/open

**Comment by joraku** [comment]
@shinichi-sesame 

以下の PR のレビューとマージをお願いします。

https://github.com/oneteam-dev/react-oneteam/pulls/assigned/shinichi-sesame

**Comment by shinichi-sesame** [comment]
@joraku 

https://github.com/oneteam-dev/react-oneteam/network/alert/yarn.lock/handlebars/open

↑ こちらは 404 になり参照できませんでした。

**Comment by shinichi-sesame** [comment]
@joraku 派生して生成されたPRに対応しました。クローズします。
