### ISSUE TITLE
Typo on the main one-team.com

### ISSUE THREAD

**Issue by Almax** [oneteam-dev/react-oneteam#9]
Hey guys, 
Just walking by and spot a typo:  [ co**n**municate ] instead of [ communicate ]- on second section
and by the way: 
you guys did a pretty neat looking service

peace\O/

**Comment by sugarshin** [comment]
Hi,
Thank you for your point out, also we'll fix it. we continue to make service better. thanks!

**Comment by sugarshin** [comment]
We fixed it, thank you!
